import Header from "@/components/header/main-header";

// const inter = Inter({ subsets: ["latin"] });
import classes from "./page.module.css"

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={classes.background} >
        <Header/>
        {children}
        </body>
    </html>
  );
}
